version: "3.6"

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:lts
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://admin:${POSTGRES_PASSWORD}@postgres:5432/smart-brain
      USER_ID: ${USER_ID}
      PAT: ${PAT}
      APP_ID: ${APP_ID}
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
    env_file:
      - .env

  # Postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
